-- =============================================================================
--  BIS-Saathi — V1__init.sql
--  Flyway baseline for PostgreSQL 17 + pgvector 0.8.6.
--
--  Covers every table named in CLAUDE.md §7, with foreign keys, indexes, unique
--  constraints and created/updated timestamps on each. Column names are the
--  contract shared with mock-api/src/db/store.ts and docs/API.md; a rename here is
--  a breaking change in three places.
--
--  Conventions
--   * ids are UUIDs generated by the database (gen_random_uuid()).
--   * every mutable table has created_at (immutable) and updated_at (trigger-fed).
--   * every user-owned row carries user_id and is queried with it in the WHERE
--     clause — never filtered after the fact (R9).
--   * money-free, timeline-free: nothing here stores a fee or a duration, because
--     none may be asserted without a source (R10).
-- =============================================================================

CREATE EXTENSION IF NOT EXISTS vector;      -- pgvector: embeddings + HNSW
CREATE EXTENSION IF NOT EXISTS pg_trgm;     -- trigram index for fuzzy title search
CREATE EXTENSION IF NOT EXISTS pgcrypto;    -- gen_random_uuid()

-- -----------------------------------------------------------------------------
-- updated_at trigger helper (§7: created/updated timestamps)
-- -----------------------------------------------------------------------------
CREATE OR REPLACE FUNCTION set_updated_at() RETURNS trigger
LANGUAGE plpgsql AS $$
BEGIN
  NEW.updated_at := now();
  RETURN NEW;
END;
$$;

-- =============================================================================
-- 1. IDENTITY AND AUTHORIZATION
-- =============================================================================

CREATE TABLE roles (
  id          smallint     PRIMARY KEY,
  name        varchar(32)  NOT NULL UNIQUE,
  description text,
  created_at  timestamptz  NOT NULL DEFAULT now(),
  updated_at  timestamptz  NOT NULL DEFAULT now(),
  -- Roles are a closed set (§4). The hierarchy ADMIN ⊃ CONTENT_MANAGER ⊃ USER is
  -- enforced in application code (RoleHierarchy), not by a column, so it cannot be
  -- silently changed by a data edit.
  CONSTRAINT roles_name_known CHECK (name IN ('USER', 'CONTENT_MANAGER', 'ADMIN'))
);

INSERT INTO roles (id, name, description) VALUES
  (1, 'USER',            'Default role for every registered account.'),
  (2, 'CONTENT_MANAGER', 'May ingest and approve knowledge; cannot read audit logs.'),
  (3, 'ADMIN',           'Implies CONTENT_MANAGER; may read audit logs and configuration.');

CREATE TABLE users (
  id                     uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  email                  varchar(254) NOT NULL,
  password_hash          varchar(255) NOT NULL,
  -- Argon2id is the default; bcrypt(12) is the documented fallback. The scheme is
  -- recorded so an old hash can be upgraded on next successful login.
  password_scheme        varchar(16)  NOT NULL DEFAULT 'argon2id'
                         CONSTRAINT users_password_scheme_known CHECK (password_scheme IN ('argon2id', 'bcrypt')),
  full_name              varchar(120) NOT NULL,
  persona                varchar(32)
                         CONSTRAINT users_persona_known CHECK (persona IS NULL OR persona IN
                           ('CONSUMER', 'MSME_MANUFACTURER', 'JEWELLER_RETAILER', 'STUDENT_ENGINEER')),
  language               varchar(8)   NOT NULL DEFAULT 'en'
                         CONSTRAINT users_language_known CHECK (language IN ('en', 'hi')),
  email_verified         boolean      NOT NULL DEFAULT false,
  failed_login_attempts  smallint     NOT NULL DEFAULT 0,
  locked_until           timestamptz,
  last_login_at          timestamptz,
  deactivated_at         timestamptz,
  created_at             timestamptz  NOT NULL DEFAULT now(),
  updated_at             timestamptz  NOT NULL DEFAULT now(),
  -- Emails are stored lowercased and looked up lowercased; the constraint makes an
  -- accidental mixed-case insert fail loudly instead of creating a second account.
  CONSTRAINT users_email_lowercase CHECK (email = lower(email))
);

CREATE UNIQUE INDEX users_email_key ON users (email);
CREATE INDEX users_locked_until_idx ON users (locked_until) WHERE locked_until IS NOT NULL;

CREATE TABLE user_roles (
  user_id    uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role_id    smallint     NOT NULL REFERENCES roles (id) ON DELETE RESTRICT,
  granted_by uuid         REFERENCES users (id) ON DELETE SET NULL,
  granted_at timestamptz  NOT NULL DEFAULT now(),
  created_at timestamptz  NOT NULL DEFAULT now(),
  updated_at timestamptz  NOT NULL DEFAULT now(),
  PRIMARY KEY (user_id, role_id)
);

CREATE INDEX user_roles_role_idx ON user_roles (role_id);

-- Rotating refresh tokens (§8). Only the SHA-256 hash is stored; the raw token
-- exists only in the HttpOnly cookie. family_id groups a rotation chain so reuse
-- detection can revoke the whole family.
CREATE TABLE refresh_tokens (
  id                   uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id              uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  family_id            uuid         NOT NULL,
  token_hash           char(64)     NOT NULL,
  expires_at           timestamptz  NOT NULL,
  used_at              timestamptz,
  revoked_at           timestamptz,
  replaced_by_token_id uuid         REFERENCES refresh_tokens (id) ON DELETE SET NULL,
  user_agent           varchar(512),
  ip                   inet,
  created_at           timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT refresh_tokens_hash_unique UNIQUE (token_hash),
  -- A token that has been used must have a replacement; that is the rotation proof.
  CONSTRAINT refresh_tokens_rotation_consistent CHECK (used_at IS NULL OR replaced_by_token_id IS NOT NULL)
);

CREATE INDEX refresh_tokens_user_idx    ON refresh_tokens (user_id) WHERE revoked_at IS NULL;
CREATE INDEX refresh_tokens_family_idx  ON refresh_tokens (family_id);
CREATE INDEX refresh_tokens_expiry_idx  ON refresh_tokens (expires_at);

-- Password reset tokens: opaque, single-use, hashed, 30-minute TTL (§8).
CREATE TABLE password_reset_tokens (
  id         uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id    uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  token_hash char(64)     NOT NULL UNIQUE,
  expires_at timestamptz  NOT NULL,
  used_at    timestamptz,
  ip         inet,
  created_at timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT password_reset_used_after_issue CHECK (used_at IS NULL OR used_at >= created_at)
);

CREATE INDEX password_reset_tokens_user_idx ON password_reset_tokens (user_id);

-- =============================================================================
-- 2. CONVERSATIONS AND MESSAGES (features #2, #3)
-- =============================================================================

CREATE TABLE conversations (
  id          uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  title       varchar(160) NOT NULL,
  summary     text,
  language    varchar(8)   NOT NULL DEFAULT 'en'
              CONSTRAINT conversations_language_known CHECK (language IN ('en', 'hi')),
  archived_at timestamptz,
  created_at  timestamptz  NOT NULL DEFAULT now(),
  updated_at  timestamptz  NOT NULL DEFAULT now()
);

-- The (user_id, updated_at) index is what makes the R9 ownership-scoped list query
-- cheap: ownership is part of the access path, not a post-filter.
CREATE INDEX conversations_user_updated_idx ON conversations (user_id, updated_at DESC);
CREATE INDEX conversations_user_archived_idx ON conversations (user_id) WHERE archived_at IS NULL;

CREATE TABLE messages (
  id               uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  conversation_id  uuid         NOT NULL REFERENCES conversations (id) ON DELETE CASCADE,
  -- Denormalised on purpose: every message query is authorised by user_id without
  -- joining through conversations (R9).
  user_id          uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  role             varchar(16)  NOT NULL
                   CONSTRAINT messages_role_known CHECK (role IN ('user', 'assistant', 'system')),
  content          text         NOT NULL,
  -- Frozen evidence for this answer: the citation validator (R3) already removed
  -- anything the model invented, so what is stored is what was shown.
  sources_json     jsonb        NOT NULL DEFAULT '[]'::jsonb,
  evidence_tier    varchar(8)   NOT NULL DEFAULT 'NONE'
                   CONSTRAINT messages_tier_known CHECK (evidence_tier IN ('STRONG', 'PARTIAL', 'NONE')),
  -- The classifier's own vocabulary, kept identical to INTENTS in the API contract:
  -- a row that says 'hallmark' would never match a query for 'hallmarking', and the
  -- CHECK is what turns that drift into a rejected write instead of silent bad data.
  intent           varchar(24)
                   CONSTRAINT messages_intent_known CHECK (intent IS NULL OR intent IN
                     ('chitchat', 'meta', 'factual', 'recommend', 'certification',
                      'hallmarking', 'lab', 'clarify', 'out_of_scope')),
  language         varchar(8)   NOT NULL DEFAULT 'en'
                   CONSTRAINT messages_language_known CHECK (language IN ('en', 'hi')),
  prompt_tokens    integer      NOT NULL DEFAULT 0,
  completion_tokens integer     NOT NULL DEFAULT 0,
  -- NULL means "this deployment has not configured pricing", which the UI renders as
  -- no cost rather than as free (R10). numeric, not real: a float would let a per-token
  -- rate accumulate rounding drift across a month of invoices.
  cost_usd         numeric(10,6),
  model            varchar(64),
  cache_hit        boolean      NOT NULL DEFAULT false,
  retrieval_ms     integer,
  follow_ups       jsonb        NOT NULL DEFAULT '[]'::jsonb,
  -- R8: a failed generation is recorded, never overwritten with a plausible answer.
  error            varchar(64),
  created_at       timestamptz  NOT NULL DEFAULT now(),
  updated_at       timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX messages_conversation_created_idx ON messages (conversation_id, created_at);
CREATE INDEX messages_user_idx                 ON messages (user_id, created_at DESC);
CREATE INDEX messages_tier_idx                 ON messages (evidence_tier) WHERE evidence_tier <> 'STRONG';
CREATE INDEX messages_sources_gin              ON messages USING gin (sources_json jsonb_path_ops);

-- =============================================================================
-- 3. KNOWLEDGE BASE (features #11-#13; R2, R7, R10, R11)
-- =============================================================================

-- Canonical standard identity. `restricted` standards are metadata-only (R11):
-- their text is never stored in knowledge_chunks.
CREATE TABLE standards (
  id                uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  standard_no       varchar(64)  NOT NULL UNIQUE,
  title             text         NOT NULL,
  title_hi          text,
  ics_code          varchar(32),
  doc_type          varchar(32)  NOT NULL DEFAULT 'IS'
                    CONSTRAINT standards_doc_type_known CHECK (doc_type IN
                      ('IS', 'QCO', 'HANDBOOK', 'CODE_OF_PRACTICE', 'SPECIFICATION', 'OTHER')),
  language          varchar(8)   NOT NULL DEFAULT 'en'
                    CONSTRAINT standards_language_known CHECK (language IN ('en', 'hi')),
  access_level      varchar(16)  NOT NULL DEFAULT 'open'
                    CONSTRAINT standards_access_known CHECK (access_level IN ('open', 'restricted')),
  -- R7: a superseded standard must not be retrievable as current guidance.
  verification_status varchar(24) NOT NULL DEFAULT 'UNVERIFIED'
                    CONSTRAINT standards_verification_known CHECK (verification_status IN
                      ('VERIFIED', 'UNVERIFIED', 'OUTDATED', 'SUPERSEDED', 'RESTRICTED')),
  published_date    date,
  revised_date      date,
  superseded_by_id  uuid         REFERENCES standards (id) ON DELETE SET NULL,
  source_url        text,
  verified_by       uuid         REFERENCES users (id) ON DELETE SET NULL,
  verified_at       timestamptz,
  created_at        timestamptz  NOT NULL DEFAULT now(),
  updated_at        timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT standards_superseded_has_status CHECK (
    superseded_by_id IS NULL OR verification_status = 'SUPERSEDED'
  )
);

CREATE INDEX standards_title_trgm  ON standards USING gin (title gin_trgm_ops);
CREATE INDEX standards_status_idx  ON standards (verification_status);
CREATE INDEX standards_ics_idx     ON standards (ics_code);

CREATE TABLE knowledge_documents (
  id                  uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  standard_id         uuid         REFERENCES standards (id) ON DELETE SET NULL,
  title               text         NOT NULL,
  standard_no         varchar(64),
  doc_type            varchar(32)  NOT NULL DEFAULT 'OTHER',
  language            varchar(8)   NOT NULL DEFAULT 'en'
                      CONSTRAINT kd_language_known CHECK (language IN ('en', 'hi')),
  access_level        varchar(16)  NOT NULL DEFAULT 'open'
                      CONSTRAINT kd_access_known CHECK (access_level IN ('open', 'restricted')),
  verification_status varchar(24)  NOT NULL DEFAULT 'UNVERIFIED'
                      CONSTRAINT kd_verification_known CHECK (verification_status IN
                        ('VERIFIED', 'UNVERIFIED', 'OUTDATED', 'SUPERSEDED', 'RESTRICTED')),
  approved_at         timestamptz,
  approved_by         uuid         REFERENCES users (id) ON DELETE SET NULL,
  created_at          timestamptz  NOT NULL DEFAULT now(),
  updated_at          timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX kd_status_idx     ON knowledge_documents (verification_status);
CREATE INDEX kd_standard_idx   ON knowledge_documents (standard_id);
CREATE INDEX kd_title_trgm     ON knowledge_documents USING gin (title gin_trgm_ops);

-- An immutable version of a document's content. Citations point here, not at
-- knowledge_documents, so a re-ingest cannot silently rewrite the evidence behind
-- an answer that has already been shown to a user (R2).
CREATE TABLE document_versions (
  id             uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id    uuid         NOT NULL REFERENCES knowledge_documents (id) ON DELETE CASCADE,
  version_no     integer      NOT NULL,
  content_hash   char(64)     NOT NULL,
  published_date date,
  revised_date   date,
  is_current     boolean      NOT NULL DEFAULT true,
  created_at     timestamptz  NOT NULL DEFAULT now(),
  updated_at     timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT dv_doc_version_unique UNIQUE (document_id, version_no)
);

CREATE INDEX dv_current_idx ON document_versions (document_id) WHERE is_current;

-- Where a document came from (R2 provenance: URL, publisher, retrieval date).
CREATE TABLE document_sources (
  id                 uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  document_version_id uuid        NOT NULL REFERENCES document_versions (id) ON DELETE CASCADE,
  source_kind        varchar(32)  NOT NULL DEFAULT 'url'
                     CONSTRAINT ds_kind_known CHECK (source_kind IN ('url', 'file', 'manual', 'api')),
  url                text,
  publisher          varchar(255),
  retrieved_at       timestamptz  NOT NULL DEFAULT now(),
  checksum           char(64),
  license_note       text,
  created_at         timestamptz  NOT NULL DEFAULT now(),
  updated_at         timestamptz  NOT NULL DEFAULT now(),
  -- R11: copyright status is recorded at ingestion time, not inferred later.
  copyright_status   varchar(24)  NOT NULL DEFAULT 'UNKNOWN'
                     CONSTRAINT ds_copyright_known CHECK (copyright_status IN
                       ('PUBLIC', 'GOVERNMENT', 'LICENSED', 'RESTRICTED', 'UNKNOWN')),
  -- Freshness monitor (§6 #13). NULL until the first check; a source with no URL has
  -- nothing to re-check and is reported as such rather than as a failure.
  last_checked_at    timestamptz,
  last_check_outcome varchar(16)
                     CONSTRAINT ds_freshness_outcome_known CHECK (last_check_outcome IS NULL OR last_check_outcome IN
                       ('UNCHANGED', 'CHANGED', 'LINK_ROT', 'ERROR')),
  last_check_detail  text
);

CREATE INDEX ds_version_idx ON document_sources (document_version_id);
-- The sweep's work list: what is due to be re-checked, oldest check first.
CREATE INDEX ds_due_check_idx ON document_sources (last_checked_at NULLS FIRST)
  WHERE url IS NOT NULL AND checksum IS NOT NULL;

-- The retrieval unit. A chunk is retrievable only when review_state = 'APPROVED'
-- and verification_status <> 'SUPERSEDED' (R7). Restricted documents produce no
-- chunks at all (R11).
CREATE TABLE knowledge_chunks (
  id                  uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id         uuid         NOT NULL REFERENCES knowledge_documents (id) ON DELETE CASCADE,
  document_version_id uuid         NOT NULL REFERENCES document_versions (id) ON DELETE CASCADE,
  ordinal             integer      NOT NULL,
  title               text         NOT NULL,
  standard_no         varchar(64),
  section             varchar(120),
  heading_path        text,
  doc_type            varchar(32)  NOT NULL DEFAULT 'OTHER',
  language            varchar(8)   NOT NULL DEFAULT 'en'
                      CONSTRAINT kc_language_known CHECK (language IN ('en', 'hi')),
  source_url          text,
  published_date      date,
  revised_date        date,
  verification_status varchar(24)  NOT NULL DEFAULT 'UNVERIFIED'
                      CONSTRAINT kc_verification_known CHECK (verification_status IN
                        ('VERIFIED', 'UNVERIFIED', 'OUTDATED', 'SUPERSEDED', 'RESTRICTED')),
  verified_by         uuid         REFERENCES users (id) ON DELETE SET NULL,
  verified_at         timestamptz,
  review_state        varchar(24)  NOT NULL DEFAULT 'PENDING_REVIEW'
                      CONSTRAINT kc_review_known CHECK (review_state IN
                        ('PENDING_REVIEW', 'APPROVED', 'REJECTED')),
  reviewed_by         uuid         REFERENCES users (id) ON DELETE SET NULL,
  reviewed_at         timestamptz,
  content             text         NOT NULL,
  content_hash        char(64)     NOT NULL,
  token_count         integer      NOT NULL DEFAULT 0,
  -- Multilingual embedding (Hindi↔English retrieval, §3). 1024 dims is the common
  -- multilingual size; changing it requires a re-embed, so it is fixed here.
  embedding           vector(1024),
  embedding_model     varchar(64),
  embedded_at         timestamptz,
  -- Postgres FTS. `simple` config, not `english`: the corpus is bilingual and an
  -- English stemmer mangles Devanagari. Hindi normalisation happens at ingest.
  tsv                 tsvector     GENERATED ALWAYS AS (
                        to_tsvector('simple', coalesce(title, '') || ' ' || coalesce(section, '') || ' ' || content)
                      ) STORED,
  metadata            jsonb        NOT NULL DEFAULT '{}'::jsonb,
  ingested_at         timestamptz  NOT NULL DEFAULT now(),
  created_at          timestamptz  NOT NULL DEFAULT now(),
  updated_at          timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT kc_doc_ordinal_unique UNIQUE (document_id, ordinal),
  CONSTRAINT kc_token_count_positive CHECK (token_count >= 0),
  -- R11: a restricted chunk is a contradiction; refuse to store one.
  CONSTRAINT kc_restricted_forbidden CHECK (verification_status <> 'RESTRICTED')
);

-- HNSW for approximate cosine search (§3). cosine, not L2: the retrieval score is
-- compared against EVIDENCE_SCORE_THRESHOLD in cosine space.
CREATE INDEX kc_embedding_hnsw ON knowledge_chunks
  USING hnsw (embedding vector_cosine_ops)
  WITH (m = 16, ef_construction = 64);
CREATE INDEX kc_tsv_gin        ON knowledge_chunks USING gin (tsv);
CREATE INDEX kc_metadata_gin   ON knowledge_chunks USING gin (metadata jsonb_path_ops);
CREATE INDEX kc_retrievable_idx ON knowledge_chunks (document_id, review_state, verification_status);
CREATE INDEX kc_language_idx   ON knowledge_chunks (language, review_state);
CREATE INDEX kc_standard_no_idx ON knowledge_chunks (standard_no);

-- The knowledge-base revision. One row, bumped by every approval and every rejection:
-- it is what invalidates the answer cache and what `kbVersion` in the SSE `usage` frame
-- reports, so a cached answer can be proven to pre-date a correction. Kept in the
-- database rather than in process memory because a restarted server must not serve
-- yesterday's cache as if nothing had changed.
CREATE TABLE app_state (
  id          smallint     PRIMARY KEY DEFAULT 1 CONSTRAINT app_state_singleton CHECK (id = 1),
  kb_version  bigint       NOT NULL DEFAULT 0 CONSTRAINT app_state_kb_non_negative CHECK (kb_version >= 0),
  updated_at  timestamptz  NOT NULL DEFAULT now()
);

INSERT INTO app_state (id, kb_version) VALUES (1, 0);

CREATE TABLE ingestion_jobs (
  id               uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  document_id      uuid         REFERENCES knowledge_documents (id) ON DELETE SET NULL,
  -- The version this job produced. Kept separate from document_id so a monitor can show
  -- "v3 is pending review" while v2 stays live and searchable (R2).
  document_version_id uuid      REFERENCES document_versions (id) ON DELETE SET NULL,
  source_kind      varchar(32)  NOT NULL DEFAULT 'url'
                   CONSTRAINT ij_kind_known CHECK (source_kind IN ('url', 'upload', 'manifest', 'manual')),
  -- URL or filename for the monitor; NULL for pasted text, which has no source to link.
  source_label     text,
  -- The four states the API returns. `DONE`, not `SUCCEEDED`: one vocabulary in the
  -- schema, the code and docs/API.md, because a monitor that has to translate states
  -- is where "FAILED" gets rendered as green.
  state            varchar(16)  NOT NULL DEFAULT 'QUEUED'
                   CONSTRAINT ij_state_known CHECK (state IN ('QUEUED', 'RUNNING', 'DONE', 'FAILED')),
  stage            varchar(32)  NOT NULL DEFAULT 'QUEUED'
                   CONSTRAINT ij_stage_known CHECK (stage IN
                     ('QUEUED', 'FETCH', 'EXTRACT', 'CLEAN', 'CHUNK', 'EMBED', 'PERSIST', 'DONE')),
  -- R8: the failure reason is kept and surfaced through /admin/ingestion/jobs.
  error            text,
  -- Non-fatal findings (OCR required, injection-like strings, dropped pages). Surfaced
  -- in the job payload rather than swallowed, but they never fail a job.
  warnings         jsonb        NOT NULL DEFAULT '[]'::jsonb,
  attempts         smallint     NOT NULL DEFAULT 0,
  max_attempts     smallint     NOT NULL DEFAULT 3,
  -- Retry backoff: NULL (or in the past) means the worker may take this job now.
  next_attempt_at  timestamptz,
  chunks_produced  integer      NOT NULL DEFAULT 0,
  requested_by     uuid         REFERENCES users (id) ON DELETE SET NULL,
  -- The request minus any pasted or uploaded payload: enough to re-run from the URL
  -- without a client round-trip. needs_resubmit says when that is not possible.
  spec             jsonb,
  needs_resubmit   boolean      NOT NULL DEFAULT false,
  started_at       timestamptz,
  finished_at      timestamptz,
  created_at       timestamptz  NOT NULL DEFAULT now(),
  updated_at       timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT ij_finished_after_started CHECK (started_at IS NULL OR finished_at IS NULL OR finished_at >= started_at),
  CONSTRAINT ij_max_attempts_positive CHECK (max_attempts > 0),
  -- A failed job is the only one that may wait for a retry, and it must say why.
  CONSTRAINT ij_failure_recorded CHECK (state <> 'FAILED' OR error IS NOT NULL)
);

CREATE INDEX ij_state_idx    ON ingestion_jobs (state, created_at DESC);
CREATE INDEX ij_document_idx ON ingestion_jobs (document_id);
-- What the worker polls: due retries, oldest first. Partial, so a queue full of
-- finished jobs does not grow the hot path.
CREATE INDEX ij_due_retry_idx ON ingestion_jobs (next_attempt_at)
  WHERE state IN ('QUEUED', 'FAILED');

-- =============================================================================
-- 4. DOMAIN REFERENCE DATA (features #6, #7, #8)
-- =============================================================================

-- BIS-recognised laboratories (feature #8). Contact details only; no claim about
-- accreditation scope beyond what a source states (R10).
CREATE TABLE laboratories (
  id                  uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  name                text         NOT NULL,
  lab_type            varchar(32)  NOT NULL DEFAULT 'BIS_RECOGNISED'
                      CONSTRAINT lab_type_known CHECK (lab_type IN
                        ('BIS_RECOGNISED', 'NABL_ACCREDITED', 'HALLMARKING_CENTRE', 'OTHER')),
  scope               text,
  address_line        text,
  city                varchar(120),
  state               varchar(120),
  pincode             varchar(12),
  country             varchar(64)  NOT NULL DEFAULT 'India',
  phone               varchar(32),
  email               varchar(254),
  source_url          text,
  verification_status varchar(24)  NOT NULL DEFAULT 'UNVERIFIED'
                      CONSTRAINT lab_verification_known CHECK (verification_status IN
                        ('VERIFIED', 'UNVERIFIED', 'OUTDATED', 'SUPERSEDED', 'RESTRICTED')),
  verified_at         timestamptz,
  created_at          timestamptz  NOT NULL DEFAULT now(),
  updated_at          timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX labs_state_city_idx ON laboratories (state, city);
CREATE INDEX labs_type_idx       ON laboratories (lab_type);

-- Step-by-step certification guidance (feature #7). Steps carry a citation; a step
-- without one cannot be published (R2/R10).
CREATE TABLE certification_guides (
  id                  uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  scheme              varchar(64)  NOT NULL,
  title               text         NOT NULL,
  title_hi            text,
  summary             text,
  steps_json          jsonb        NOT NULL DEFAULT '[]'::jsonb,
  documents_json      jsonb        NOT NULL DEFAULT '[]'::jsonb,
  standard_id         uuid         REFERENCES standards (id) ON DELETE SET NULL,
  source_url          text,
  language            varchar(8)   NOT NULL DEFAULT 'en'
                      CONSTRAINT cg_language_known CHECK (language IN ('en', 'hi')),
  verification_status varchar(24)  NOT NULL DEFAULT 'UNVERIFIED'
                      CONSTRAINT cg_verification_known CHECK (verification_status IN
                        ('VERIFIED', 'UNVERIFIED', 'OUTDATED', 'SUPERSEDED', 'RESTRICTED')),
  verified_at         timestamptz,
  created_at          timestamptz  NOT NULL DEFAULT now(),
  updated_at          timestamptz  NOT NULL DEFAULT now(),
  -- Fees and timelines are only present if a cited source states them (R10).
  fee_note            text,
  timeline_note       text
);

CREATE UNIQUE INDEX cg_scheme_language_idx ON certification_guides (scheme, language);
CREATE INDEX cg_standard_idx ON certification_guides (standard_id);

-- =============================================================================
-- 5. USER-OWNED DATA (R9: every one of these is queried with user_id in the WHERE)
-- =============================================================================

CREATE TABLE saved_standards (
  id          uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  standard_id uuid         NOT NULL REFERENCES standards (id) ON DELETE CASCADE,
  note        text,
  created_at  timestamptz  NOT NULL DEFAULT now(),
  updated_at  timestamptz  NOT NULL DEFAULT now(),
  CONSTRAINT saved_standards_unique UNIQUE (user_id, standard_id)
);

CREATE INDEX saved_standards_user_idx ON saved_standards (user_id, created_at DESC);

CREATE TABLE product_profiles (
  id          uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id     uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  name        varchar(160) NOT NULL,
  category    varchar(120),
  hs_code     varchar(16),
  material    varchar(160),
  intended_use text,
  attributes  jsonb        NOT NULL DEFAULT '{}'::jsonb,
  created_at  timestamptz  NOT NULL DEFAULT now(),
  updated_at  timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX product_profiles_user_idx ON product_profiles (user_id, created_at DESC);

CREATE TABLE compliance_reports (
  id                uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id           uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  product_profile_id uuid        REFERENCES product_profiles (id) ON DELETE SET NULL,
  conversation_id   uuid         REFERENCES conversations (id) ON DELETE SET NULL,
  title             varchar(200) NOT NULL,
  -- R5: every generated report is informational and carries the disclaimer.
  body_markdown     text         NOT NULL,
  sources_json      jsonb        NOT NULL DEFAULT '[]'::jsonb,
  evidence_tier     varchar(8)   NOT NULL DEFAULT 'NONE'
                    CONSTRAINT cr_tier_known CHECK (evidence_tier IN ('STRONG', 'PARTIAL', 'NONE')),
  language          varchar(8)   NOT NULL DEFAULT 'en'
                    CONSTRAINT cr_language_known CHECK (language IN ('en', 'hi')),
  generated_at      timestamptz  NOT NULL DEFAULT now(),
  created_at        timestamptz  NOT NULL DEFAULT now(),
  updated_at        timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX cr_user_idx ON compliance_reports (user_id, created_at DESC);

CREATE TABLE watchlist (
  id           uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id      uuid         NOT NULL REFERENCES users (id) ON DELETE CASCADE,
  standard_id  uuid         REFERENCES standards (id) ON DELETE CASCADE,
  keyword      varchar(200),
  notify_on    varchar(32)  NOT NULL DEFAULT 'REVISION'
               CONSTRAINT wl_notify_known CHECK (notify_on IN ('REVISION', 'SUPERSESSION', 'ANY_CHANGE')),
  last_notified_at timestamptz,
  created_at   timestamptz  NOT NULL DEFAULT now(),
  updated_at   timestamptz  NOT NULL DEFAULT now(),
  -- A watchlist entry tracks either a standard or a keyword, never neither.
  CONSTRAINT watchlist_has_target CHECK (standard_id IS NOT NULL OR keyword IS NOT NULL)
);

CREATE INDEX watchlist_user_idx     ON watchlist (user_id, created_at DESC);
CREATE INDEX watchlist_standard_idx ON watchlist (standard_id);

CREATE TABLE feedback (
  id             uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id        uuid         REFERENCES users (id) ON DELETE SET NULL,
  message_id     uuid         REFERENCES messages (id) ON DELETE SET NULL,
  conversation_id uuid        REFERENCES conversations (id) ON DELETE SET NULL,
  rating         smallint     CONSTRAINT fb_rating_known CHECK (rating IS NULL OR rating BETWEEN 1 AND 5),
  helpful        boolean,
  comment        text,
  -- Feedback about a wrong answer is the highest-value signal for eval/golden.jsonl.
  issue_type     varchar(32)
                 CONSTRAINT fb_issue_known CHECK (issue_type IS NULL OR issue_type IN
                   ('WRONG_ANSWER', 'MISSING_SOURCE', 'STALE_SOURCE', 'LANGUAGE', 'OTHER')),
  resolved       boolean      NOT NULL DEFAULT false,
  created_at     timestamptz  NOT NULL DEFAULT now(),
  updated_at     timestamptz  NOT NULL DEFAULT now(),
  -- One verdict per user per message. The endpoint upserts rather than appending, so a
  -- person who changes their mind edits their feedback instead of voting twice.
  CONSTRAINT fb_user_message_unique UNIQUE (user_id, message_id)
);

CREATE INDEX feedback_message_idx ON feedback (message_id);
CREATE INDEX feedback_user_idx    ON feedback (user_id, created_at DESC);
CREATE INDEX feedback_open_idx    ON feedback (created_at DESC) WHERE resolved = false;

-- Questions the knowledge base could not answer. This is the coverage-gap signal
-- for P0 ingestion planning — it records the question, never a fabricated answer.
CREATE TABLE gap_queries (
  id            uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  user_id       uuid         REFERENCES users (id) ON DELETE SET NULL,
  conversation_id uuid       REFERENCES conversations (id) ON DELETE SET NULL,
  query_text    text         NOT NULL,
  language      varchar(8)   NOT NULL DEFAULT 'en'
                CONSTRAINT gq_language_known CHECK (language IN ('en', 'hi')),
  intent        varchar(24),
  occurred_at   timestamptz  NOT NULL DEFAULT now(),
  created_at    timestamptz  NOT NULL DEFAULT now(),
  updated_at    timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX gap_queries_recent_idx ON gap_queries (occurred_at DESC);
CREATE INDEX gap_queries_intent_idx ON gap_queries (intent);

-- =============================================================================
-- 6. AUDIT (§8: security-relevant events; ADMIN-only read)
-- =============================================================================

CREATE TABLE audit_logs (
  id            uuid         PRIMARY KEY DEFAULT gen_random_uuid(),
  actor_user_id uuid         REFERENCES users (id) ON DELETE SET NULL,
  actor_roles   jsonb        NOT NULL DEFAULT '[]'::jsonb,
  action        varchar(64)  NOT NULL,
  entity_type   varchar(48),
  entity_id     varchar(64),
  outcome       varchar(16)  NOT NULL DEFAULT 'SUCCESS'
                CONSTRAINT al_outcome_known CHECK (outcome IN ('SUCCESS', 'DENIED', 'FAILURE')),
  ip            inet,
  user_agent    varchar(512),
  trace_ref     varchar(32),
  metadata      jsonb        NOT NULL DEFAULT '{}'::jsonb,
  created_at    timestamptz  NOT NULL DEFAULT now(),
  updated_at    timestamptz  NOT NULL DEFAULT now()
);

CREATE INDEX audit_logs_created_idx ON audit_logs (created_at DESC);
CREATE INDEX audit_logs_actor_idx   ON audit_logs (actor_user_id, created_at DESC);
CREATE INDEX audit_logs_action_idx  ON audit_logs (action, created_at DESC);
CREATE INDEX audit_logs_denied_idx  ON audit_logs (created_at DESC) WHERE outcome <> 'SUCCESS';

-- =============================================================================
-- 7. updated_at TRIGGERS
-- =============================================================================

DO $$
DECLARE
  t text;
BEGIN
  FOREACH t IN ARRAY ARRAY[
    'roles', 'users', 'user_roles', 'conversations', 'messages',
    'standards', 'knowledge_documents', 'document_versions', 'document_sources',
    'knowledge_chunks', 'ingestion_jobs', 'laboratories', 'certification_guides',
    'saved_standards', 'product_profiles', 'compliance_reports', 'watchlist',
    'feedback', 'gap_queries', 'audit_logs'
  ]
  LOOP
    EXECUTE format('CREATE TRIGGER %I BEFORE UPDATE ON %I FOR EACH ROW EXECUTE FUNCTION set_updated_at()',
                   t || '_set_updated_at', t);
  END LOOP;
END;
$$;

-- refresh_tokens and password_reset_tokens are append-only: they deliberately have
-- no updated_at and no trigger, because mutating a token row would destroy the
-- evidence that reuse detection depends on.
